M48
; DRILL file {KiCad (6.0.0-0)} date Monday, December 05, 2022 at 10:13:47 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-05T10:13:47-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.4646Y-3.3371
X3.4646Y-5.0694
X5.315Y-3.3371
X5.315Y-5.0694
T0
M30
