M48
; DRILL file {KiCad (6.0.0-0)} date Monday, February 07, 2022 at 01:40:14 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-07T13:40:14-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X5.3477Y-4.43
T2
X5.0Y-4.48
X5.1Y-4.48
X5.2Y-4.48
X5.3Y-4.48
X5.4Y-4.48
X5.5Y-4.48
T0
M30
