M48
; DRILL file {KiCad (6.0.0-0)} date Monday, December 05, 2022 at 03:29:07 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-05T15:29:07-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.9193Y-2.2343
X1.9193Y-4.1831
X5.8661Y-2.2343
X5.8661Y-4.1831
T0
M30
