M48
; DRILL file {KiCad (6.0.0-0)} date Sunday, September 25, 2022 at 10:13:58 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-25T22:13:58-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.9685Y-2.2441
X1.9685Y-4.0551
X5.8268Y-2.2441
X5.8268Y-4.0551
T0
M30
