(part "RKJXV1224005"
    (packageRef "RKJXV1224005")
    (interface
        (port "1" (symbPinId 1) (portName "MH1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "MH2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "MH3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "MH4") (portType INOUT))
        (port "A1" (symbPinId 5) (portName "CCW_1") (portType INOUT))
        (port "A2" (symbPinId 6) (portName "WIPER_1") (portType INOUT))
        (port "A3" (symbPinId 7) (portName "CW_1") (portType INOUT))
        (port "B1" (symbPinId 8) (portName "CCW_2") (portType INOUT))
        (port "B2" (symbPinId 9) (portName "WIPER_2") (portType INOUT))
        (port "B3" (symbPinId 10) (portName "CW_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "ALPS Electric")
    (property "Manufacturer_Part_Number" "RKJXV1224005")
    (property "Mouser_Part_Number" "688-RKJXV1224005")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Alps-Alpine/RKJXV1224005?qs=RiQAlOPxzzAqLSX9lUzx8Q%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Plugin,13x13mm Multi-Directional Switches ROHS, Rotary Potentiometer, 10 kOhm, 1Turn, 12.5 mW")
    (property "Datasheet_Link" "https://tech.alpsalpine.com/e/products/detail/RKJXV1224005/")
    (property "symbolName1" "RKJXV1224005")
)
