M48
; DRILL file {KiCad (6.0.0-0)} date Friday, September 02, 2022 at 11:48:09 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-02T11:48:09-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.0315Y-2.4016
X3.0315Y-4.0551
X5.8268Y-2.4016
X5.8268Y-4.0551
T0
M30
