M48
; DRILL file {KiCad (6.0.0-0)} date Monday, December 05, 2022 at 01:27:34 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-05T13:27:34-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.4736Y-3.3426
X2.4803Y-5.2169
X5.2461Y-5.2185
X5.3261Y-3.3426
T0
M30
